version: 2.1
jobs:
  build_and_test:
    docker:
    - image: mcr.microsoft.com/dotnet/sdk:9.0
    environment:
      TEST_RESULTS_DIR: test-results
    steps:
      - checkout
      - run:
          name: Build
          command: dotnet build
      - run:
          name: Test
          command: |
            dotnet test \
              --no-build \
              --logger "trx;LogFileName=results.trx" \
              --results-directory "./$TEST_RESULTS_DIR"
      - run:
          name: "Install trx2junit and Convert Test Results"
          command: |
            dotnet tool install -g trx2junit
            export PATH="$PATH:/root/.dotnet/tools"
            trx2junit "./$TEST_RESULTS_DIR/*.trx"
      - store_test_results:
          path: "./$TEST_RESULTS_DIR"

workflows:
  build:
    jobs:
      - build_and_test