version: 2.1
jobs:
  build:
    docker: 
      - image: mcr.microsoft.com/dotnet/sdk:9.0
    steps:
      - checkout
      - run:
          name: Build
          command: dotnet build --configuration Release

  unit-test:
    parameters:
      output-test-dir:
        type: string
        default: test-results
        description: 'test results directory'
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:9.0
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: |
            dotnet test \
              --configuration Release \
              --filter "Categoty=Unit" \
              --logger "trx;LogFileName=results.trx" \
              --results-directory "./<< parameters.output-test-dir >>"
      - run:
          name: Install trx2junit and Convert Test Results
          command: |
            dotnet tool install -g trx2junit
            export PATH="$PATH:/root/.dotnet/tools"
            trx2junit "./<< parameters.output-test-dir >>/*.trx"
      - store_test_results:
          path: "./<< parameters.output-test-dir >>"
          

workflows:
  build-unit-test:
    jobs:
      - build
      - unit-test:
          requires:
            - build